 name: LOSTY

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "chiragbhatnagar@gmail.com"
  GitHubName: "losthacker00@" 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          chmod +x bgmi 
          pip install telebot 
          pip install aiohttp 
          pip install flask 
          pip install pymongo 
          pip install pytz
          pip install aiogram
          python Danger.py
