name: Alive Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *" # This runs the workflow every 10 minutes

jobs:
  alive-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Run a script to check pipeline status
      run: |
        echo "This workflow is defined in main.yml"
        echo "The pipeline is alive!"

    - name: Run min.yml
      run: |
        echo "Running main.yml"
        # Add the appropriate command to run main.yml based on your use case
        # Example: if using Ansible, you might run:
        ansible-playbook main.yml

        # Or, if it's a shell script, you might use:
        bash main.yml
