iname: Run Danger Script 24/7

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Set the appropriate Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telebot pymongo certifi aiohttp pytz psutil

    - name: Run Danger Script
      run: |
        chmod +x bgmi
        nohup python Danger.py &  # Run the script in the background
        while true; do sleep 60; done  # Keep the GitHub action alive by sleeping in a loop
        
